Aerticket:
  DataAnonymizer:
    defaults:
      anonymizeAfter: '30 days'
      anonymizedValues:
        'fallback': null
        'string': 'Anonymized'
        'integer': 0
        'array': null

Neos:
  Flow:
    log:
      aerticketDataAnonymizerLogger:
        logger: Neos\Flow\Log\Logger
        backend: Neos\Flow\Log\Backend\FileBackend
        backendOptions:
          logFileURL: '%FLOW_PATH_DATA%Logs/DataAnonymizer.log'
          createParentDirectories: true
          severityThreshold: '%LOG_INFO%'
          maximumLogFileSize: 10485760
          logFilesToKeep: 1
          logMessageOrigin: false
