Aerticket:
  DataAnonymizer:
    defaults:
      anonymizeAfter: '30 days'
      anonymizedValues:
        'fallback': null
        'string': 'Anonymized'
        'integer': 0
        'array': null

Neos:
  Flow:
    log:
      psr3:
        Neos\Flow\Log\PsrLoggerFactory:
          aerticketDataAnonymizerLogger:
            default:
              class: Neos\Flow\Log\Backend\FileBackend
              options:
                createParentDirectories: true
                logFileURL: '%FLOW_PATH_DATA%Logs/DataAnonymizer.log'
                severityThreshold: '%LOG_DEBUG%'
                maximumLogFileSize: 10485760
                logFilesToKeep: 1
                logMessageOrigin: false
